### ISSUE TITLE
Bug: `Display Header Language Tags` setting not work on mobile

### ISSUE THREAD

**Issue by magicdmer** [mayurankv/Obsidian-Code-Styler#99]
## Describe the bug
set `Display Header Language Tags`  to `never`， PC is ok， mobile will always show Language tag

### Environment
- Plugin Version: 1.0.7
- Obsidian Version:  1.3.7
- Platform:  Mobile
- OS:  MIUI14 (android 13)
- Theme:  blue topaz

**Comment by mayurankv** [comment]
Hi, thanks once again for a helpful bug report, I appreciate it greatly! Unfortunately, I find it quite difficult to develop for mobile since I'm not used to how desktop and mobile differ and also because I'm currently only testing on my phone which is a bit of a struggle.

Since the plug-in still has a few outstanding issues that are quite important, this is likely going to take some time to get round to. I hope that's not an issue!

If it's something you'd find particularly useful to be resolved I can try look at it a bit sooner so please let me know if that's the case!

**Comment by mayurankv** [comment]
See #20

**Comment by magicdmer** [comment]
This bug does not currently affect my usage,  you can fix more important bugs first

**Comment by mayurankv** [comment]
Btw, is this still an issue, not sure if refactors may have removed it?

**Comment by magicdmer** [comment]
Test ok
